WebMarket.Web/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebMarket.DataAccess.Services;
using WebMarket.DataAccess.Services.Interface;
using WebMarket.Models;

namespace WebMarket.Web.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> CategoryList = _categoryService.GetAll();
            return View(CategoryList);
        }

        //Get
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //post
        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "مقدار فیلد ترتیب نمایش نباید با مقدار فیلد نام برابر باشد");
            }

            if (ModelState.IsValid)
            {
                _categoryService.Add(obj);
                TempData["success"] = "دسته جدید با موفقیت ایجاد شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var categoryFromDb = _db.Categories.Find(id);
            var categoryFromDbFirst = _categoryService.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //post
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "مقدار فیلد ترتیب نمایش نباید با مقدار فیلد نام برابر باشد");
            }

            if (ModelState.IsValid)
            {
                _categoryService.Update(obj);
                TempData["success"] = "دسته با موفقیت ویرایش شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }


            var categoryFromDbFirst = _categoryService.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }

            return View(categoryFromDbFirst);
        }

        //post
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _categoryService.GetFirstOrDefault(u => u.Id == id);
            _categoryService.Remove(obj);
            TempData["success"] = "دسته با موفقیت حذف شد";
            return RedirectToAction("Index");
        }

    }
}

WebMarket.Web/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using WebMarket.DataAccess.Services;
using WebMarket.DataAccess.Services.Interface;
using WebMarket.Models;

namespace WebMarket.Web.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;

        public CompanyController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        public IActionResult Index()
        {
            IEnumerable<Company> companies = _companyService.GetAll();
            return View(companies);
        }

        //Get
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //post
        [HttpPost]
        public IActionResult Create(Company obj)
        {

            if (ModelState.IsValid)
            {
                _companyService.Add(obj);
                TempData["success"] = "کمپانی جدید با موفقیت ایجاد شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var companyFromDbFirst = _companyService.GetFirstOrDefault(u => u.Id == id);

            if (companyFromDbFirst == null)
            {
                return NotFound();
            }

            return View(companyFromDbFirst);
        }

        //post
        [HttpPost]
        public IActionResult Edit(Company obj)
        {

            if (ModelState.IsValid)
            {
                _companyService.Update(obj);
                TempData["success"] = "کمپانی با موفقیت ویرایش شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }


            var companyFromDbFirst = _companyService.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (companyFromDbFirst == null)
            {
                return NotFound();
            }

            return View(companyFromDbFirst);
        }

        //post
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _companyService.GetFirstOrDefault(u => u.Id == id);
            _companyService.Remove(obj);
            TempData["success"] = "کمپانی با موفقیت حذف شد";
            return RedirectToAction("Index");
        }

    }
}

WebMarket.Web/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Mvc;
using WebMarket.DataAccess.Services;
using WebMarket.DataAccess.Services.Interface;
using WebMarket.Models;

namespace WebMarket.Web.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly ICoverTypeService _coverTypeService;

        public CoverTypeController(ICoverTypeService coverTypeService)
        {
            _coverTypeService = coverTypeService;
        }

        public IActionResult Index()
        {
            IEnumerable<CoverType> CoverTypeList = _coverTypeService.GetAll();
            return View(CoverTypeList);
        }

        //Get
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //post
        [HttpPost]
        public IActionResult Create(CoverType obj)
        {

            if (ModelState.IsValid)
            {
                _coverTypeService.Add(obj);
                TempData["success"] = "تایپ جدید با موفقیت ایجاد شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Get
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var categoryFromDb = _db.Categories.Find(id);
            var coverTypeFromDbFirst = _coverTypeService.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (coverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(coverTypeFromDbFirst);
        }

        //post
        [HttpPost]
        public IActionResult Edit(CoverType obj)
        {

            if (ModelState.IsValid)
            {
                _coverTypeService.Update(obj);
                TempData["success"] = "تایپ با موفقیت ویرایش شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //Get
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }


            var coverTypeFromDbFirst = _coverTypeService.GetFirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (coverTypeFromDbFirst == null)
            {
                return NotFound();
            }

            return View(coverTypeFromDbFirst);
        }

        //post
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _coverTypeService.GetFirstOrDefault(u => u.Id == id);
            _coverTypeService.Remove(obj);
            TempData["success"] = "تایپ با موفقیت حذف شد";
            return RedirectToAction("Index");
        }

    }
}

WebMarket.Web/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMarket.DataAccess.Services.Interface;
using WebMarket.Models.ViewModels;

namespace WebMarket.Web.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;
        private readonly ICoverTypeService _coverTypeService;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IProductService productService
            , ICategoryService categoryService, ICoverTypeService coverTypeService, 
            IWebHostEnvironment hostEnvironment)
        {
            _productService = productService;
            _categoryService = categoryService;
            _coverTypeService = coverTypeService;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        //Get
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _categoryService.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _coverTypeService.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                //create
                //ViewBag.CategoryList = CategoryList;
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(productVM);
            }
            else
            {
                //update
                productVM.Product = _productService.GetFirstOrDefault(u => u.Id == id);
                return View(productVM);
            }


            return View(productVM);
        }

        //post
        [HttpPost]
        public IActionResult Upsert(ProductVM obj, IFormFile? file)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (ModelState.IsValid)
            {
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\products");
                    var extenstion = Path.GetExtension(file.FileName);

                    if(obj.Product.ImgeUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImgeUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStrems = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create))
                    {
                        file.CopyTo(fileStrems);
                    }

                    obj.Product.ImgeUrl = fileName + extenstion;
                }

                if (obj.Product.Id == 0) _productService.Add(obj);
                else _productService.Update(obj.Product);

                TempData["success"] = "محصول با موفقیت ویرایش شد";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


 
        #region API CALL
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _productService.GetAll();
            return Json(new { data = productList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _productService.GetFirstOrDefault(u => u.Id == id);
            if(obj == null)
            {
                return Json(new { success = false, message = "خطا در حذف " });
            }
            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImgeUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _productService.Remove(obj);
            return Json(new { success = true, message = "حذف موفقیت آمیز بود" });
        }
        #endregion

    }
}

WebMarket.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMarket.Web</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <!-- bootstrap 5 rtl -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    <!-- bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- toastr styles -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <!-- font iransans -->
    <link rel="stylesheet" href="~/fonts/css/style.css" />
    <!-- custom styles for admin panel -->
    <link rel="stylesheet" href="~/css/AdminCustomStyles.css" />
     <!-- data table -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
</head>
<body dir="rtl">

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="Customer" asp-controller="Home" asp-action="Index">وب مارکت <i class="bi bi-award-fill"></i></a>
    </nav>
    <div id="layoutSidenav">

         <!-- SideBar-->
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">محصولات</div>
                        <a class="nav-link" asp-area="Admin" asp-controller="Product" asp-action="Index">
                            مدیریت محصولات
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                            مدیریت دسته ها
                        </a>
                        <a class="nav-link" asp-area="Admin" asp-controller="CoverType" asp-action="Index">
                            مدیریت کاور تایپ ها
                        </a>
                                             <a class="nav-link" asp-area="Admin" asp-controller="Company" asp-action="Index">
                            مدیریت کمپانی ها
                        </a>
                                             <a class="nav-link" asp-area="Admin" asp-controller="ShoppingCart" asp-action="Index">
                            مدیریت سبدهای خرید 
                        </a>
                    </div>
                </div>
@*                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>*@
            </nav>
        </div>

         <!-- Content-->
        <div id="layoutSidenav_content">

            <main role="main" class="pb-3">
                @RenderBody()
            </main>

            <!-- Footer-->
            <footer class="py-4 bg-dark mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <p class="m-0 text-center text-white">
                            تمامی حقوق مادی و معنوی این سایت متعلق به <a class="text-light" href="http://abolfazlbarzegar.ir" target="_blank">ابوالفضــل برزگـر</a> میباشد.
                        </p>
                        <div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
     <!-- sweet alert -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
     <!-- data table -->
      <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebMarket.Web/Areas/Admin/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>

    <script type="text/javascript">
        toastr.success(' @TempData["success"]')
     </script>
}